# This file should not be used as is - instead should be used via Make which
# rewrites the below to match the current build environment.

version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ARG_DOCKERFILE
    image: ARG_IMAGE
    volumes:
      - ARG_PWD/.go:/go
      - ARG_PWD:/go/src/ARG_PKG
      - ARG_PWD/bin:/go/bin
      - ARG_PWD/.go/std:/usr/local/go/pkg/linux_amd64_static
      - ARG_PWD/.go/cache:/.cache/go-build
    working_dir: /go/src/ARG_PKG
    ports:
      - "3001:3001"
    command: /go/bin/ARG_BIN server
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGPASSWORD=password
      - PGUSER=kuzu
      - KUZU_DATABASE_URL=postgres://kuzu:password@postgres:5432/kuzu_development?sslmode=disable

  postgres:
    build:
      context: ./docker/postgres
    ports:
      - "5432"
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=kuzu
      - POSTGRES_DB=postgres
      - DATABASES=kuzu_development,kuzu_test

volumes:
  postgres_vol: