DROP TABLE IF EXISTS public.channels CASCADE;
DROP TABLE IF EXISTS public.data_sources CASCADE;
DROP TABLE IF EXISTS public.applications CASCADE;
DROP TABLE IF EXISTS public.things CASCADE;
DROP TABLE IF EXISTS public.identities CASCADE;
DROP TABLE IF EXISTS public.users;