ALTER TABLE things
  ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
  ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE identities
  ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE applications
  ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;